language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.0
services:
  - postgresql
addons:
  postgresql: "9.5"
cache:
  yarn: true
  directories:
    - _build
    - deps
    - node_modules
sudo: required
before_script:
  - mix deps.get --only test
  - psql -c 'create database xperiments_test;' -U postgres
  - nvm install 6.10.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --silent > /dev/null
script:
  - mix test
